import argparse

import gcsfs
import pandas as pd
from tqdm import tqdm


# This script generates replicate to sample mapping file to interpret the qc report. It
# was developed as an alternative to extract_rep_names_from_encode.sh which might not
# work if the pipeline run_dir had outputs for a specific condition in multiple
# workflow ids, this happens when a workflow is rerun on gcp, where the metadata.json
# file generated by caper points to the completed paths from failed workflow ids. This
# script uses the croo.filetable.*.tsv to generate the mapping file.
#
# Updated to support the new single-level croo output structure where label directories
# sit directly under gcp_path (no intermediate workflow ID subdirectory).

# Usage: python3 encode_rep_names_from_croo.py
# <gcp_path_to_croo_outputs> <gcp_output_bucket_path> <gcp_project>


def main(gcp_path: str, output_path: str, gcp_project: str):
    fs = gcsfs.GCSFileSystem(project=gcp_project)

    # List label directories directly under croo output path
    label_dirs = [p for p in fs.ls(gcp_path.removeprefix("gs://")) if fs.isdir(p)]

    cond_l = []
    rep_l = []
    sample_list = []

    for label_dir in (pbar := tqdm(label_dirs)):
        label = label_dir.rstrip("/").split("/")[-1]
        pbar.set_description(f"Processing {label}")

        in_path = fs.glob(f"{label_dir}/croo.filetable*.tsv")
        pbar.write(f"Found {len(in_path)} filetable files: {in_path}")

        if len(in_path) == 0:
            pbar.write(f"WARNING: no filetable found for {label}, skipping")
            continue

        filetable_filename = f"gs://{in_path[0]}"

        df_in = pd.read_csv(filetable_filename, sep="\t", header=None)
        filtered = df_in[df_in[0].str.contains("Raw BAM from aligner")]

        cond = filetable_filename.split("/")[-2]

        for vals in filtered[1]:
            split_vals = vals.split("/")
            cond_l.append(cond)
            rep = split_vals[-2]
            rep_l.append(rep)
            sample = (split_vals[-1]).split("_R1.trim.bam")[0]
            sample_list.append(sample)

        pbar.write(f"Found {len(filtered[1])} values, finished {label}\n")

    out_df = pd.DataFrame()
    out_df["cond_l"] = cond_l
    out_df["rep_l"] = rep_l
    out_df["sample_list"] = sample_list

    print(out_df.head())
    out_file = f"{output_path.rstrip('/')}/rep_to_sample_map.csv"
    out_df.to_csv(out_file, index=False, header=False)

    print("Success! Finished writing the mapping file")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="This script generates the replicate to sample mapping file to "
        "interpret the qc report"
    )
    parser.add_argument("gcp_path", help="location of atac-seq croo outputs", type=str)
    parser.add_argument(
        "output_path",
        help="output path, where you want the outputs to be written",
        type=str,
    )
    parser.add_argument("gcp_project", help="GCP project ID")

    args = parser.parse_args()

    main(args.gcp_path, args.output_path, args.gcp_project)
